/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActivityKind = "call" | "email" | "meeting" | "note" | "stage_change" | "system" | "visit" | "whatsapp";

export type AestheticSessionStatus = "canceled" | "completed" | "in_progress" | "planned";

export type AppointmentOrigin = "import" | "online_booking" | "phone" | "reception" | "recurrence" | "waitlist" | "whatsapp";

export type AppointmentStatus = "arrived" | "canceled" | "completed" | "confirmed" | "in_progress" | "no_show" | "scheduled";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type AutomationChannel = "email" | "in_app" | "sms" | "task" | "webhook" | "whatsapp";

export type AutomationRunStatus = "canceled" | "failed" | "scheduled" | "sent" | "skipped";

export type AutomationTrigger = "appointment_completed" | "appointment_created" | "appointment_no_show" | "appointment_upcoming" | "installment_due" | "installment_overdue" | "lead_created" | "lot_expiring" | "orthodontic_maintenance_due" | "patient_birthday" | "patient_inactive" | "quote_accepted" | "quote_cooling" | "quote_sent" | "session_followup_due" | "stock_below_minimum" | "temperature_breach";

export type BlockReason = "holiday" | "lunch" | "maintenance" | "other" | "personal" | "training" | "vacation";

export type CashMovementKind = "adjustment" | "payment" | "refund" | "supply" | "withdrawal";

export type CashSessionStatus = "audited" | "closed" | "open";

export type ClaimBatchStatus = "canceled" | "open" | "settled" | "submitted";

export type ClaimDenialStatus = "appealed" | "expired" | "open" | "recovered" | "written_off";

export type ClaimStatus = "batched" | "canceled" | "open" | "settled" | "submitted";

export type ClinicalDocumentKind = "certificate" | "consent_term" | "other" | "prescription" | "referral_letter" | "treatment_report";

export type ClinicalFileKind = "document" | "exam_report" | "other" | "photo_after" | "photo_before" | "photo_clinical" | "radiograph" | "scan_3d";

export type CommissionBasis = "gross_price" | "margin" | "net_price" | "received";

export type CommissionStatus = "approved" | "canceled" | "paid" | "pending";

export type CommissionTrigger = "on_execution" | "on_payment";

export type ConfirmationChannel = "app" | "email" | "phone" | "sms" | "whatsapp";

export type ConfirmationOutcome = "confirmed" | "declined" | "failed" | "no_answer" | "pending";

export type ConsentKind = "compartilhamento_terceiros" | "comunicacao_marketing" | "procedimento" | "tratamento_dados" | "uso_imagem";

export type ConversationStatus = "closed" | "open" | "pending" | "snoozed";

export type DataRequestKind = "anonymize" | "delete" | "export" | "rectify";

export type DataRequestStatus = "completed" | "in_progress" | "received" | "rejected";

export type DocumentStatus = "canceled" | "delivered" | "draft" | "issued" | "signed";

export type FormKind = "anamnesis" | "anamnesis_hof" | "custom" | "evaluation" | "protocol" | "satisfaction";

export type GatewayChargeStatus = "authorized" | "canceled" | "created" | "expired" | "failed" | "paid" | "pending" | "refunded";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ImportKind = "patient";

export type ImportRowStatus = "duplicate" | "error" | "imported" | "valid";

export type ImportStatus = "analyzing" | "applied" | "canceled" | "ready";

export type InjectableUnit = "cm2" | "fio" | "ml" | "sessao" | "U";

export type InstallmentStatus = "canceled" | "open" | "paid" | "partially_paid" | "renegotiated";

/** Centavos e contadores. O parser do driver converte int8 para number. */
export type Int8 = ColumnType<number, bigint | number | string, bigint | number | string>;

export type InventoryCountStatus = "canceled" | "closed" | "counting" | "draft";

export type JobStatus = "canceled" | "done" | "failed" | "running" | "scheduled";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LeadStatus = "converted" | "disqualified" | "new" | "qualified" | "working";

export type MaintenanceStatus = "canceled" | "done" | "missed" | "scheduled";

export type MembershipStatus = "active" | "invited" | "removed" | "suspended";

export type MessageDirection = "inbound" | "outbound";

export type MessageStatus = "deleted" | "delivered" | "failed" | "queued" | "read" | "sent";

export type NotificationKind = "clinical" | "critical" | "financial" | "info" | "mention" | "task" | "warning";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OdontogramEntryStatus = "canceled" | "executed" | "existing" | "planned";

export type OpportunityStatus = "lost" | "open" | "won";

export type OrthodonticStatus = "abandoned" | "active" | "completed" | "planning" | "retention" | "transferred";

export type OutboxStatus = "discarded" | "failed" | "pending" | "processing" | "sent";

export type PatientSignalKind = "birthday" | "cooling_quote" | "followup_due" | "inactive_patient" | "maintenance_due" | "no_show_risk" | "open_quote" | "overdue_installment" | "overdue_return" | "pending_treatment";

export type PatientStatus = "active" | "anonymized" | "archived" | "inactive";

export type PayableStatus = "canceled" | "open" | "paid" | "partially_paid";

export type PayerBillingMode = "invoiced" | "reimbursement";

export type PayerKind = "agreement" | "insurance" | "partnership" | "private";

export type PaymentKind = "boleto" | "cash" | "credit" | "credit_note" | "debit" | "insurance" | "pix" | "transfer";

export type PaymentStatus = "confirmed" | "reversed";

export type PlanItemStatus = "canceled" | "executed" | "planned" | "scheduled";

export type PriceListStatus = "active" | "archived" | "draft";

export type ProcedureScope = "arch" | "general" | "quadrant" | "region" | "session" | "surface" | "tooth";

export type ProductKind = "consumable" | "equipment" | "injectable" | "instrument" | "medication" | "retail";

export type PurchaseOrderStatus = "canceled" | "draft" | "partially_received" | "received" | "sent";

export type QuoteStatus = "accepted" | "canceled" | "draft" | "expired" | "negotiating" | "rejected" | "sent";

export type ReceivableOrigin = "manual" | "membership_fee" | "orthodontic" | "product_sale" | "quote" | "treatment_plan";

export type ReceivableStatus = "canceled" | "open" | "paid" | "partially_paid" | "renegotiated";

export type ReconciliationStatus = "divergent" | "ignored" | "matched" | "unmatched";

export type ReferralStatus = "contacted" | "converted" | "lost" | "registered" | "rewarded" | "scheduled";

export type ResourceKind = "chair" | "equipment" | "room";

export type StockMovementKind = "adjustment" | "consumption" | "loss" | "purchase" | "return" | "sale" | "transfer_in" | "transfer_out";

export type TaskStatus = "canceled" | "done" | "open";

export type TemplateStatus = "approved" | "disabled" | "draft" | "paused" | "pending" | "rejected";

export type TenantStatus = "active" | "canceled" | "past_due" | "suspended" | "trial";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

/** Data sem hora, no formato 'YYYY-MM-DD'. Nunca vira Date: ver scripts/gen-db-types.mjs. */
export type DateOnly = ColumnType<string, Date | string, Date | string>;

export type ToothCondition = "bridge_pontic" | "caries" | "crown" | "extraction_indicated" | "fractured" | "healthy" | "impacted" | "implant" | "missing" | "mobility" | "periapical_lesion" | "prosthesis" | "restoration" | "root_canal" | "sealant";

export type ToothSurface = "C" | "D" | "I" | "L" | "M" | "O" | "P" | "V";

export type TreatmentPlanStatus = "active" | "canceled" | "completed" | "draft" | "suspended";

export type WaitlistStatus = "canceled" | "expired" | "offered" | "scheduled" | "waiting";

export interface AcquisitionSource {
  channel: Generated<string>;
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
  tenant_id: string;
}

export interface Activity {
  body: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: Generated<ActivityKind>;
  lead_id: string | null;
  occurred_at: Generated<Timestamp>;
  opportunity_id: string | null;
  outcome: string | null;
  patient_id: string | null;
  performed_by: string | null;
  subject: string | null;
  tenant_id: string;
}

export interface AestheticProtocol {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  recommended_interval_days: number | null;
  tenant_id: string;
  version: Generated<number>;
}

export interface AestheticProtocolStep {
  id: Generated<string>;
  notes: string | null;
  procedure_id: string | null;
  product_id: string | null;
  protocol_id: string;
  quantity_unit: string | null;
  region_code: string | null;
  sort_order: number;
  suggested_quantity: Numeric | null;
  technique: string | null;
  tenant_id: string;
}

export interface AestheticSession {
  adverse_event: string | null;
  anesthesia: string | null;
  appointment_id: string | null;
  created_at: Generated<Timestamp>;
  followup_done_at: Timestamp | null;
  followup_due_on: DateOnly | null;
  id: Generated<string>;
  next_session_suggested_on: DateOnly | null;
  notes: string | null;
  patient_id: string;
  performed_at: Timestamp | null;
  protocol_id: string | null;
  provider_id: string;
  satisfaction_score: number | null;
  session_number: Generated<number>;
  status: Generated<AestheticSessionStatus>;
  tenant_id: string;
  treatment_plan_id: string | null;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Appointment {
  arrived_at: Timestamp | null;
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  canceled_by: string | null;
  completed_at: Timestamp | null;
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  ends_at: Timestamp;
  id: Generated<string>;
  no_show_at: Timestamp | null;
  no_show_risk: Numeric | null;
  notes: string | null;
  origin: Generated<AppointmentOrigin>;
  orthodontic_case_id: string | null;
  patient_id: string;
  period: Generated<string | null>;
  procedure_id: string | null;
  provider_id: string;
  started_at: Timestamp | null;
  starts_at: Timestamp;
  status: Generated<AppointmentStatus>;
  tenant_id: string;
  treatment_plan_item_id: string | null;
  unit_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AppointmentConfirmation {
  appointment_id: string;
  channel: ConfirmationChannel;
  created_at: Generated<Timestamp>;
  hours_before: number;
  id: Generated<string>;
  message_id: string | null;
  outcome: Generated<ConfirmationOutcome>;
  responded_at: Timestamp | null;
  sent_at: Timestamp | null;
  tenant_id: string;
}

export interface AppointmentStatusHistory {
  appointment_id: string;
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  from_status: AppointmentStatus | null;
  id: Generated<string>;
  reason: string | null;
  tenant_id: string;
  to_status: AppointmentStatus;
}

export interface AppUser {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string;
  email_verified_at: Timestamp | null;
  failed_login_count: Generated<number>;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  mfa_enabled_at: Timestamp | null;
  mfa_secret: string | null;
  password_hash: string | null;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AuditLog {
  action: string;
  actor_id: string | null;
  actor_role: string | null;
  after_data: Json | null;
  before_data: Json | null;
  changed_keys: string[] | null;
  entity: string;
  entity_id: string | null;
  entity_key: string | null;
  id: Generated<string>;
  ip_address: string | null;
  occurred_at: Generated<Timestamp>;
  request_id: string | null;
  tenant_id: string;
  unit_id: string | null;
  user_agent: string | null;
}

export interface AutomationRule {
  assignee_id: string | null;
  channel: AutomationChannel;
  conditions: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_per_patient_per_day: Generated<number>;
  name: string;
  offset_minutes: Generated<number>;
  send_on_weekend: Generated<boolean>;
  send_window_end: Generated<string>;
  send_window_start: Generated<string>;
  template_id: string | null;
  tenant_id: string;
  trigger_event: AutomationTrigger;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AutomationRun {
  created_at: Generated<Timestamp>;
  error_message: string | null;
  executed_at: Timestamp | null;
  id: Generated<string>;
  message_id: string | null;
  outbox_id: string | null;
  patient_id: string | null;
  rule_id: string;
  scheduled_for: Timestamp;
  skip_reason: string | null;
  status: Generated<AutomationRunStatus>;
  target_entity: string;
  target_id: string;
  tenant_id: string;
}

export interface BankAccount {
  account: string | null;
  bank_code: string | null;
  branch: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  tenant_id: string;
  unit_id: string | null;
}

export interface BankStatementEntry {
  account_id: string;
  amount_cents: Int8;
  description: string | null;
  external_id: string | null;
  id: Generated<string>;
  imported_at: Generated<Timestamp>;
  matched_at: Timestamp | null;
  matched_by: string | null;
  payable_id: string | null;
  payment_id: string | null;
  posted_on: DateOnly;
  raw_payload: Json | null;
  status: Generated<ReconciliationStatus>;
  tenant_id: string;
}

export interface BodyRegion {
  area_group: string;
  code: string;
  is_facial: Generated<boolean>;
  map_x: Numeric | null;
  map_y: Numeric | null;
  name_pt: string;
  risk_notes: string | null;
  side: string | null;
  sort_order: Generated<number>;
}

export interface Campaign {
  budget_cents: Generated<Int8>;
  channel: string;
  created_at: Generated<Timestamp>;
  ends_on: DateOnly | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  spend_cents: Generated<Int8>;
  starts_on: DateOnly | null;
  tenant_id: string;
}

export interface CashMovement {
  amount_cents: Int8;
  category_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  kind: CashMovementKind;
  payment_id: string | null;
  session_id: string;
  tenant_id: string;
}

export interface CashSession {
  closed_at: Timestamp | null;
  closed_by: string | null;
  counted_cents: Int8 | null;
  difference_cents: Generated<Int8 | null>;
  expected_cents: Int8 | null;
  id: Generated<string>;
  notes: string | null;
  opened_at: Generated<Timestamp>;
  opened_by: string;
  opening_cents: Generated<Int8>;
  status: Generated<CashSessionStatus>;
  tenant_id: string;
  unit_id: string;
}

export interface Claim {
  authorization_code: string | null;
  authorization_valid_until: DateOnly | null;
  batch_id: string | null;
  billed_cents: Generated<Int8>;
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  denied_cents: Generated<Int8>;
  id: Generated<string>;
  issued_on: Generated<DateOnly>;
  notes: string | null;
  number: Int8 | null;
  paid_cents: Generated<Int8>;
  patient_id: string;
  payer_id: string;
  provider_id: string | null;
  quote_id: string | null;
  status: Generated<ClaimStatus>;
  tenant_id: string;
  unit_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ClaimBatch {
  billed_cents: Generated<Int8>;
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  code: string | null;
  competence: DateOnly;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  notes: string | null;
  paid_cents: Generated<Int8>;
  payer_id: string;
  remittance_date: DateOnly | null;
  status: Generated<ClaimBatchStatus>;
  submitted_at: Timestamp | null;
  submitted_by: string | null;
  tenant_id: string;
  unit_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ClaimDenial {
  amount_cents: Int8;
  appeal_deadline: DateOnly | null;
  appeal_notes: string | null;
  appealed_at: Timestamp | null;
  claim_id: string;
  claim_item_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  reason: string;
  reason_code: string | null;
  recovered_cents: Generated<Int8>;
  resolution_notes: string | null;
  resolved_at: Timestamp | null;
  status: Generated<ClaimDenialStatus>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ClaimItem {
  billed_cents: Int8;
  claim_id: string;
  created_at: Generated<Timestamp>;
  denied_cents: Generated<Int8 | null>;
  description: string;
  id: Generated<string>;
  paid_cents: Int8 | null;
  procedure_id: string | null;
  quantity: Generated<Numeric>;
  quote_item_id: string | null;
  region_code: string | null;
  settled_at: Timestamp | null;
  sort_order: Generated<number>;
  surfaces: Generated<ArrayType<ToothSurface>>;
  tenant_id: string;
  tooth_code: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ClinicalDocument {
  appointment_id: string | null;
  body: string;
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  content_hash: string | null;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  delivery_channel: string | null;
  file_url: string | null;
  id: Generated<string>;
  kind: ClinicalDocumentKind;
  number: Int8 | null;
  patient_id: string;
  provider_id: string;
  signature_evidence: Json | null;
  signed_at: Timestamp | null;
  signed_by: string | null;
  status: Generated<DocumentStatus>;
  tenant_id: string;
  title: string;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ClinicalFile {
  aesthetic_session_id: string | null;
  appointment_id: string | null;
  caption: string | null;
  capture_metadata: Json | null;
  checksum_sha256: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  file_name: string;
  id: Generated<string>;
  kind: ClinicalFileKind;
  mime_type: string;
  patient_id: string;
  size_bytes: Int8 | null;
  storage_key: string;
  taken_at: Generated<Timestamp>;
  tenant_id: string;
  uploaded_by: string | null;
}

export interface ClinicalNote {
  amendment_reason: string | null;
  amends_note_id: string | null;
  appointment_id: string | null;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  locked_at: Timestamp | null;
  patient_id: string;
  provider_id: string;
  signature_hash: string | null;
  signature_ip: string | null;
  signed_at: Timestamp | null;
  tenant_id: string;
  unit_id: string | null;
}

export interface CommissionEntry {
  amount_cents: Int8;
  approved_at: Timestamp | null;
  approved_by: string | null;
  base_cents: Int8;
  basis: CommissionBasis;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  injectable_application_id: string | null;
  membership_id: string;
  notes: string | null;
  paid_at: Timestamp | null;
  payable_id: string | null;
  payment_id: string | null;
  percent: Numeric | null;
  quote_item_id: string | null;
  reference_month: DateOnly;
  rule_id: string | null;
  status: Generated<CommissionStatus>;
  tenant_id: string;
  treatment_plan_item_id: string | null;
  unit_id: string;
}

export interface CommissionRule {
  basis: Generated<CommissionBasis>;
  category_id: string | null;
  created_at: Generated<Timestamp>;
  fixed_cents: Int8 | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  membership_id: string | null;
  payer_id: string | null;
  percent: Numeric | null;
  priority: Generated<number>;
  procedure_id: string | null;
  tenant_id: string;
  trigger_event: Generated<CommissionTrigger>;
  unit_id: string | null;
  valid_from: Generated<DateOnly>;
  valid_to: DateOnly | null;
}

export interface ConsentDocument {
  body: string;
  body_hash: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  effective_from: Generated<Timestamp>;
  effective_to: Timestamp | null;
  id: Generated<string>;
  kind: ConsentKind;
  legal_basis: string;
  requires_signature: Generated<boolean>;
  tenant_id: string;
  title: string;
  version: number;
}

export interface Conversation {
  account_id: string;
  assigned_to: string | null;
  closed_at: Timestamp | null;
  contact_name: string | null;
  contact_phone: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_inbound_at: Timestamp | null;
  last_outbound_at: Timestamp | null;
  lead_id: string | null;
  patient_id: string | null;
  snoozed_until: Timestamp | null;
  status: Generated<ConversationStatus>;
  tenant_id: string;
  unit_id: string | null;
  unread_count: Generated<number>;
  updated_at: Generated<Timestamp>;
  window_expires_at: Timestamp | null;
}

export interface CostCenter {
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  tenant_id: string;
  unit_id: string | null;
}

export interface FinancialCategory {
  code: string;
  direction: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  parent_id: string | null;
  tenant_id: string;
}

export interface FormResponse {
  alerts: Generated<string[]>;
  answers: Generated<Json>;
  appointment_id: string | null;
  created_at: Generated<Timestamp>;
  filled_by: string | null;
  filled_by_patient: Generated<boolean>;
  form_template_id: string;
  id: Generated<string>;
  patient_id: string;
  signature_hash: string | null;
  signed_at: Timestamp | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface FormTemplate {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: FormKind;
  name: string;
  published_at: Timestamp | null;
  schema: Json;
  tenant_id: string;
  version: Generated<number>;
}

export interface GatewayCharge {
  amount_cents: Int8;
  barcode: string | null;
  checkout_url: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  external_id: string | null;
  fee_cents: Generated<Int8>;
  id: Generated<string>;
  idempotency_key: string;
  installment_id: string | null;
  kind: PaymentKind;
  net_cents: Generated<Int8 | null>;
  paid_at: Timestamp | null;
  provider: string;
  qr_code: string | null;
  raw_payload: Json | null;
  receivable_id: string | null;
  settlement_on: DateOnly | null;
  status: Generated<GatewayChargeStatus>;
  tenant_id: string;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ImportJob {
  applied_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  duplicate_rows: Generated<number>;
  error_rows: Generated<number>;
  filename: string | null;
  id: Generated<string>;
  imported_rows: Generated<number>;
  kind: Generated<ImportKind>;
  status: Generated<ImportStatus>;
  tenant_id: string;
  total_rows: Generated<number>;
  unit_id: string;
  updated_at: Generated<Timestamp>;
  valid_rows: Generated<number>;
}

export interface ImportRow {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  job_id: string;
  line_number: number;
  message: string | null;
  patient_id: string | null;
  raw: Json;
  status: ImportRowStatus;
  tenant_id: string;
}

export interface InboundEvent {
  event_type: string | null;
  external_id: string;
  id: Generated<string>;
  payload: Json;
  processed_at: Timestamp | null;
  received_at: Generated<Timestamp>;
  signature_ok: Generated<boolean>;
  source: string;
  tenant_id: string | null;
}

export interface InjectableApplication {
  applied_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  depth: string | null;
  dilution: string | null;
  id: Generated<string>;
  lot_expires_on: DateOnly | null;
  lot_number: string | null;
  needle_gauge: string | null;
  notes: string | null;
  patient_id: string;
  points: Generated<Json>;
  product_id: string | null;
  product_lot_id: string | null;
  provider_id: string;
  quantity: Numeric;
  quantity_unit: InjectableUnit;
  region_code: string;
  session_id: string;
  stock_movement_id: string | null;
  technique: string | null;
  tenant_id: string;
  unit_cost_cents: Generated<Int8>;
  unit_price_cents: Generated<Int8>;
}

export interface Installment {
  amount_cents: Int8;
  canceled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  due_on: DateOnly;
  dunning_count: Generated<number>;
  gateway_charge_id: string | null;
  id: Generated<string>;
  last_dunning_at: Timestamp | null;
  number: number;
  paid_at: Timestamp | null;
  paid_cents: Generated<Int8>;
  patient_id: string;
  payment_method_id: string | null;
  receivable_id: string;
  status: Generated<InstallmentStatus>;
  tenant_id: string;
  total_count: number;
  unit_id: string;
  updated_at: Generated<Timestamp>;
}

export interface InventoryCount {
  closed_at: Timestamp | null;
  closed_by: string | null;
  id: Generated<string>;
  location_id: string | null;
  notes: string | null;
  started_at: Generated<Timestamp>;
  started_by: string | null;
  status: Generated<InventoryCountStatus>;
  tenant_id: string;
  unit_id: string;
}

export interface InventoryCountItem {
  adjustment_movement_id: string | null;
  counted_at: Timestamp | null;
  counted_by: string | null;
  counted_quantity: Numeric | null;
  difference: Generated<Numeric | null>;
  expected_quantity: Generated<Numeric>;
  id: Generated<string>;
  inventory_count_id: string;
  lot_id: string | null;
  product_id: string;
  tenant_id: string;
}

export interface Invitation {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by: string | null;
  revoked_at: Timestamp | null;
  role_id: string;
  tenant_id: string;
  token_hash: string;
}

export interface InvitationUnit {
  invitation_id: string;
  unit_id: string;
}

export interface Job {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  kind: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  payload: Generated<Json>;
  run_at: Generated<Timestamp>;
  status: Generated<JobStatus>;
  tenant_id: string | null;
}

export interface Lead {
  campaign_id: string | null;
  converted_at: Timestamp | null;
  converted_patient_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  disqualify_reason: string | null;
  email: string | null;
  full_name: string;
  id: Generated<string>;
  interest: string | null;
  owner_id: string | null;
  phone: string;
  source_id: string | null;
  status: Generated<LeadStatus>;
  tenant_id: string;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
  utm_campaign: string | null;
  utm_content: string | null;
  utm_medium: string | null;
  utm_source: string | null;
}

export interface LossReason {
  category: Generated<string>;
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  tenant_id: string;
}

export interface Membership {
  agenda_color: Generated<string>;
  council_number: string | null;
  council_state: string | null;
  council_type: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  ended_at: DateOnly | null;
  id: Generated<string>;
  is_provider: Generated<boolean>;
  role_id: string;
  specialty: string | null;
  started_at: Generated<DateOnly>;
  status: Generated<MembershipStatus>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface MembershipUnit {
  is_primary: Generated<boolean>;
  membership_id: string;
  unit_id: string;
}

export interface Message {
  automation_rule_id: string | null;
  billed_cents: Generated<Int8>;
  body: string | null;
  content_type: Generated<string>;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  direction: MessageDirection;
  error_code: string | null;
  error_message: string | null;
  id: Generated<string>;
  media_mime: string | null;
  media_url: string | null;
  provider_message_id: string | null;
  read_at: Timestamp | null;
  reply_to_id: string | null;
  sent_at: Timestamp | null;
  sent_by: string | null;
  status: Generated<MessageStatus>;
  template_id: string | null;
  template_variables: Json | null;
  tenant_id: string;
}

export interface MessageTemplate {
  approved_at: Timestamp | null;
  body: string;
  category: string;
  code: string;
  components: Json | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  language: Generated<string>;
  name: string;
  provider_name: string | null;
  rejection_reason: string | null;
  status: Generated<TemplateStatus>;
  tenant_id: string;
  variables: Generated<Json>;
  version: Generated<number>;
}

export interface MetricSnapshot {
  active_patients: Generated<number>;
  appointments_canceled: Generated<number>;
  appointments_completed: Generated<number>;
  appointments_no_show: Generated<number>;
  appointments_total: Generated<number>;
  cogs_cents: Generated<Int8>;
  commission_cents: Generated<Int8>;
  computed_at: Generated<Timestamp>;
  granularity: Generated<string>;
  id: Generated<string>;
  leads_created: Generated<number>;
  new_patients: Generated<number>;
  occupancy_percent: Numeric | null;
  opportunities_lost: Generated<number>;
  opportunities_won: Generated<number>;
  overdue_cents: Generated<Int8>;
  quotes_accepted_cents: Generated<Int8>;
  quotes_sent_cents: Generated<Int8>;
  reference_date: DateOnly;
  revenue_billed_cents: Generated<Int8>;
  revenue_received_cents: Generated<Int8>;
  tenant_id: string;
  unit_id: string | null;
}

export interface Notification {
  action_url: string | null;
  body: string | null;
  created_at: Generated<Timestamp>;
  dismissed_at: Timestamp | null;
  entity: string | null;
  entity_id: string | null;
  id: Generated<string>;
  kind: Generated<NotificationKind>;
  membership_id: string | null;
  read_at: Timestamp | null;
  role_id: string | null;
  tenant_id: string;
  title: string;
  unit_id: string | null;
}

export interface NotificationPreference {
  email: Generated<boolean>;
  in_app: Generated<boolean>;
  kind: NotificationKind;
  membership_id: string;
  push: Generated<boolean>;
  whatsapp: Generated<boolean>;
}

export interface OdontogramEntry {
  appointment_id: string | null;
  condition: ToothCondition;
  id: Generated<string>;
  notes: string | null;
  patient_id: string;
  provider_id: string | null;
  recorded_at: Generated<Timestamp>;
  source: Generated<string>;
  status: Generated<OdontogramEntryStatus>;
  superseded_at: Timestamp | null;
  superseded_by: string | null;
  surfaces: Generated<ArrayType<ToothSurface>>;
  tenant_id: string;
  tooth_code: string;
  treatment_plan_item_id: string | null;
}

export interface Opportunity {
  amount_cents: Generated<Int8>;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  expected_close_on: DateOnly | null;
  id: Generated<string>;
  last_activity_at: Timestamp | null;
  lead_id: string | null;
  loss_notes: string | null;
  loss_reason_id: string | null;
  next_action_at: Timestamp | null;
  owner_id: string | null;
  patient_id: string | null;
  pipeline_id: string;
  source_id: string | null;
  stage_changed_at: Generated<Timestamp>;
  stage_id: string;
  status: Generated<OpportunityStatus>;
  tenant_id: string;
  title: string;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface OpportunityStageHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  from_stage_id: string | null;
  id: Generated<string>;
  opportunity_id: string;
  seconds_in_previous_stage: Int8 | null;
  tenant_id: string;
  to_stage_id: string;
}

export interface OrthodonticCase {
  appliance_type: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  expected_end_on: DateOnly | null;
  expected_months: number | null;
  id: Generated<string>;
  installed_on: DateOnly | null;
  maintenance_interval_days: Generated<number>;
  malocclusion_class: string | null;
  monthly_fee_cents: Generated<Int8>;
  notes: string | null;
  patient_id: string;
  provider_id: string | null;
  removed_on: DateOnly | null;
  status: Generated<OrthodonticStatus>;
  technique: string;
  tenant_id: string;
  treatment_plan_id: string | null;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface OrthodonticMaintenance {
  appointment_id: string | null;
  case_id: string;
  created_at: Generated<Timestamp>;
  due_on: DateOnly;
  id: Generated<string>;
  installment_id: string | null;
  notes: string | null;
  performed_at: Timestamp | null;
  performed_by: string | null;
  sequence: number;
  status: Generated<MaintenanceStatus>;
  tenant_id: string;
  wire_used: string | null;
}

export interface OutboxMessage {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  payload: Json;
  processed_at: Timestamp | null;
  status: Generated<OutboxStatus>;
  tenant_id: string;
  topic: string;
}

export interface Patient {
  anonymized_at: Timestamp | null;
  birth_date: DateOnly | null;
  city: string | null;
  code: Generated<Int8>;
  complement: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  district: string | null;
  email: string | null;
  first_visit_at: Timestamp | null;
  full_name: string;
  gender: string | null;
  id: Generated<string>;
  last_visit_at: Timestamp | null;
  lifetime_value_cents: Generated<Int8>;
  national_id: string | null;
  next_appointment_at: Timestamp | null;
  no_show_count: Generated<number>;
  no_show_risk: Numeric | null;
  notes: string | null;
  number: string | null;
  open_balance_cents: Generated<Int8>;
  origin_unit_id: string | null;
  phone: string;
  photo_url: string | null;
  preferred_name: string | null;
  source_id: string | null;
  state_code: string | null;
  status: Generated<PatientStatus>;
  street: string | null;
  tax_id: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  visit_count: Generated<number>;
  zip_code: string | null;
}

export interface PatientConsent {
  collected_by: string | null;
  consent_document_id: string;
  device_fingerprint: string | null;
  granted_at: Generated<Timestamp>;
  id: Generated<string>;
  ip_address: string | null;
  patient_id: string;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  signature_image_url: string | null;
  signed_by_responsible_id: string | null;
  signed_hash: string | null;
  tenant_id: string;
  user_agent: string | null;
}

export interface PatientContact {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  kind: string;
  label: string | null;
  opted_out_at: Timestamp | null;
  patient_id: string;
  tenant_id: string;
  value: string;
}

export interface PatientCredit {
  amount_cents: Int8;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_on: DateOnly | null;
  id: Generated<string>;
  notes: string | null;
  origin: string;
  patient_id: string;
  tenant_id: string;
  used_cents: Generated<Int8>;
}

export interface PatientDataRequest {
  completed_at: Timestamp | null;
  due_at: Generated<Timestamp>;
  export_file_url: string | null;
  handled_by: string | null;
  id: Generated<string>;
  kind: DataRequestKind;
  notes: string | null;
  patient_id: string;
  rejection_reason: string | null;
  requested_at: Generated<Timestamp>;
  status: Generated<DataRequestStatus>;
  tenant_id: string;
}

export interface PatientProviderLink {
  first_at: Generated<Timestamp>;
  last_at: Generated<Timestamp>;
  membership_id: string;
  patient_id: string;
  relation: Generated<string>;
  tenant_id: string;
}

export interface PatientResponsible {
  created_at: Generated<Timestamp>;
  email: string | null;
  full_name: string;
  id: Generated<string>;
  is_financial: Generated<boolean>;
  is_legal: Generated<boolean>;
  patient_id: string;
  phone: string | null;
  relationship: string;
  tax_id: string | null;
  tenant_id: string;
}

export interface PatientSignal {
  assigned_to: string | null;
  computed_at: Generated<Timestamp>;
  due_on: DateOnly | null;
  entity: string | null;
  entity_id: string | null;
  id: Generated<string>;
  kind: PatientSignalKind;
  patient_id: string;
  reason: string;
  resolution: string | null;
  resolved_at: Timestamp | null;
  severity: Generated<number>;
  tenant_id: string;
  unit_id: string | null;
  value_cents: Generated<Int8>;
}

export interface PatientTag {
  patient_id: string;
  tag_id: string;
  tagged_at: Generated<Timestamp>;
  tagged_by: string | null;
  tenant_id: string;
}

export interface Payable {
  category_id: string | null;
  commission_batch_id: string | null;
  cost_center_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  document_number: string | null;
  due_on: DateOnly;
  id: Generated<string>;
  is_recurring: Generated<boolean>;
  paid_cents: Generated<Int8>;
  paid_on: DateOnly | null;
  purchase_order_id: string | null;
  recurrence_rule: string | null;
  status: Generated<PayableStatus>;
  supplier_id: string | null;
  tenant_id: string;
  total_cents: Int8;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Payer {
  admin_fee_percent: Generated<Numeric>;
  ans_code: string | null;
  /**
   * Prazo para recorrer de glosa, contado da data do demonstrativo de repasse.
   */
  appeal_days: Generated<number>;
  /**
   * Decide quem deve o dinheiro. Muda o financeiro inteiro, nao so a tabela de preco.
   */
  billing_mode: Generated<PayerBillingMode>;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: Generated<PayerKind>;
  name: string;
  notes: string | null;
  settlement_days: Generated<number>;
  tax_id: string | null;
  tenant_id: string;
}

export interface Payment {
  /**
   * Principal: abate a parcela. Nunca inclui multa nem juros.
   */
  amount_cents: Int8;
  cash_session_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  fee_cents: Generated<Int8>;
  /**
   * Multa de mora recebida junto. Nao abate a parcela.
   */
  fine_cents: Generated<Int8>;
  gateway_charge_id: string | null;
  /**
   * O que o paciente entregou: principal + multa + juros.
   */
  gross_cents: Generated<Int8 | null>;
  id: Generated<string>;
  installment_id: string;
  /**
   * Juros de mora recebidos junto. Nao abatem a parcela.
   */
  interest_cents: Generated<Int8>;
  /**
   * O que sobra para a clinica depois da taxa do meio de pagamento.
   */
  net_cents: Generated<Int8 | null>;
  notes: string | null;
  paid_at: Generated<Timestamp>;
  patient_id: string;
  payment_method_id: string;
  receipt_number: Int8 | null;
  reversal_reason: string | null;
  reversed_at: Timestamp | null;
  reverses_payment_id: string | null;
  settlement_on: DateOnly | null;
  status: Generated<PaymentStatus>;
  tenant_id: string;
  unit_id: string;
}

export interface PaymentMethod {
  affects_cash_session: Generated<boolean>;
  fee_fixed_cents: Generated<Int8>;
  fee_percent: Generated<Numeric>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: PaymentKind;
  max_installments: Generated<number>;
  name: string;
  requires_gateway: Generated<boolean>;
  settlement_days: Generated<number>;
  sort_order: Generated<number>;
  tenant_id: string;
}

export interface Permission {
  action: string;
  description: string;
  /**
   * Permissao que da acesso a dado de saude: exige MFA e gera phi_access_log.
   */
  is_phi: Generated<boolean>;
  key: string;
  resource: string;
}

export interface PhiAccessLog {
  actor_id: string;
  entity: string;
  entity_id: string | null;
  id: Generated<string>;
  ip_address: string | null;
  occurred_at: Generated<Timestamp>;
  patient_id: string;
  purpose: string;
  request_id: string | null;
  tenant_id: string;
  unit_id: string | null;
}

export interface PhotoSet {
  captured_at: Generated<Timestamp>;
  captured_by: string | null;
  created_at: Generated<Timestamp>;
  days_after: number | null;
  id: Generated<string>;
  moment: string;
  notes: string | null;
  patient_id: string;
  session_id: string | null;
  tenant_id: string;
}

export interface PhotoSetFile {
  clinical_file_id: string;
  photo_set_id: string;
  pose: string | null;
  sort_order: Generated<number>;
}

export interface Pipeline {
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_default: Generated<boolean>;
  name: string;
  tenant_id: string;
  vertical: Generated<string>;
}

export interface PipelineStage {
  code: string;
  cooling_days: Generated<number>;
  id: Generated<string>;
  is_lost: Generated<boolean>;
  is_won: Generated<boolean>;
  name: string;
  pipeline_id: string;
  sort_order: number;
  tenant_id: string;
  win_probability: Generated<Numeric>;
}

export interface PlanFeature {
  enabled: Generated<boolean>;
  feature_key: string;
  limit_value: number | null;
  plan_id: string;
}

export interface PrescriptionItem {
  document_id: string;
  dosage: string;
  drug_name: string;
  duration: string | null;
  frequency: string | null;
  id: Generated<string>;
  instructions: string | null;
  is_controlled: Generated<boolean>;
  presentation: string | null;
  quantity: string | null;
  route: string | null;
  sort_order: Generated<number>;
  tenant_id: string;
}

export interface PriceList {
  activated_at: Timestamp | null;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
  payer_id: string | null;
  status: Generated<PriceListStatus>;
  tenant_id: string;
  unit_id: string | null;
  valid_from: Generated<DateOnly>;
  valid_to: DateOnly | null;
  validity: Generated<string | null>;
  version: Generated<number>;
}

export interface PriceListItem {
  commission_percent: Numeric | null;
  expected_cost_cents: Generated<Int8>;
  floor_price_cents: Int8 | null;
  id: Generated<string>;
  max_discount_percent: Generated<Numeric>;
  /**
   * Co-participacao: a parte do paciente. O convenio paga price_cents - patient_share_cents.
   */
  patient_share_cents: Generated<Int8>;
  price_cents: Int8;
  price_list_id: string;
  procedure_id: string;
  tenant_id: string;
}

export interface Procedure {
  category_id: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  default_duration_minutes: Generated<number>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_recurring: Generated<boolean>;
  name: string;
  pricing_unit: Generated<string>;
  requires_consent_kind: ConsentKind | null;
  requires_lot: Generated<boolean>;
  scope: Generated<ProcedureScope>;
  tenant_id: string;
  tuss_code: string | null;
  updated_at: Generated<Timestamp>;
  vertical: Generated<string>;
}

export interface ProcedureBom {
  auto_consume: Generated<boolean>;
  id: Generated<string>;
  is_optional: Generated<boolean>;
  notes: string | null;
  procedure_id: string;
  product_id: string;
  quantity: Numeric;
  tenant_id: string;
  unit: string;
  waste_percent: Generated<Numeric>;
}

export interface ProcedureCategory {
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  parent_id: string | null;
  sort_order: Generated<number>;
  tenant_id: string;
  vertical: Generated<string>;
}

export interface Product {
  anvisa_code: string | null;
  brand: string | null;
  code: string;
  conversion_factor: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  default_cost_cents: Generated<Int8>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: Generated<ProductKind>;
  lead_time_days: Generated<number>;
  max_quantity: Numeric | null;
  max_temperature: Numeric | null;
  min_quantity: Generated<Numeric>;
  min_temperature: Numeric | null;
  name: string;
  requires_lot: Generated<boolean>;
  requires_refrigeration: Generated<boolean>;
  stock_unit: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  usage_unit: string;
}

export interface ProductLot {
  blocked_reason: string | null;
  created_at: Generated<Timestamp>;
  expires_on: DateOnly;
  id: Generated<string>;
  invoice_number: string | null;
  is_blocked: Generated<boolean>;
  lot_number: string;
  manufactured_on: DateOnly | null;
  product_id: string;
  received_on: Generated<DateOnly>;
  supplier_id: string | null;
  tenant_id: string;
  unit_cost_cents: Generated<Int8>;
}

export interface ProviderAvailability {
  created_at: Generated<Timestamp>;
  ends_at: string;
  id: Generated<string>;
  membership_id: string;
  slot_minutes: Generated<number>;
  starts_at: string;
  tenant_id: string;
  unit_id: string;
  valid_from: Generated<DateOnly>;
  valid_to: DateOnly | null;
  weekday: number;
}

export interface PurchaseOrder {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expected_on: DateOnly | null;
  id: Generated<string>;
  number: Int8 | null;
  payable_id: string | null;
  received_on: DateOnly | null;
  status: Generated<PurchaseOrderStatus>;
  supplier_id: string | null;
  tenant_id: string;
  total_cents: Generated<Int8>;
  unit_id: string;
}

export interface PurchaseOrderItem {
  id: Generated<string>;
  lot_id: string | null;
  product_id: string;
  purchase_order_id: string;
  quantity: Numeric;
  received_quantity: Generated<Numeric>;
  tenant_id: string;
  unit_cost_cents: Generated<Int8>;
}

export interface Quote {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  discount_approved_at: Timestamp | null;
  discount_approved_by: string | null;
  discount_cents: Generated<Int8>;
  down_payment_cents: Generated<Int8>;
  expected_cost_cents: Generated<Int8>;
  id: Generated<string>;
  installment_count: Generated<number>;
  last_interaction_at: Timestamp | null;
  loss_notes: string | null;
  loss_reason_id: string | null;
  notes: string | null;
  number: Generated<Int8>;
  /**
   * De qual negocio do funil esta proposta saiu. Aceitar o orcamento ganha a oportunidade.
   */
  opportunity_id: string | null;
  patient_id: string;
  payer_id: string | null;
  price_list_id: string | null;
  provider_id: string | null;
  rejected_at: Timestamp | null;
  sent_at: Timestamp | null;
  signature_image_url: string | null;
  signed_by_responsible_id: string | null;
  signed_hash: string | null;
  signed_ip: string | null;
  signed_user_agent: string | null;
  status: Generated<QuoteStatus>;
  subtotal_cents: Generated<Int8>;
  tenant_id: string;
  title: string | null;
  total_cents: Generated<Int8 | null>;
  unit_id: string;
  updated_at: Generated<Timestamp>;
  valid_until: DateOnly | null;
}

export interface QuoteItem {
  commission_percent: Numeric | null;
  created_at: Generated<Timestamp>;
  description: string;
  discount_cents: Generated<Int8>;
  id: Generated<string>;
  /**
   * Co-participacao congelada na emissao. Unitaria, como unit_price_cents.
   */
  patient_share_cents: Generated<Int8>;
  phase_label: string | null;
  phase_order: Generated<number>;
  price_list_item_id: string | null;
  procedure_id: string | null;
  quantity: Generated<Numeric>;
  quantity_unit: Generated<string>;
  quote_id: string;
  region_code: string | null;
  sort_order: Generated<number>;
  surfaces: Generated<ArrayType<ToothSurface>>;
  tenant_id: string;
  tooth_code: string | null;
  total_cents: Generated<Int8 | null>;
  unit_cost_cents: Generated<Int8>;
  unit_price_cents: Int8;
}

export interface QuoteStatusHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  from_status: QuoteStatus | null;
  id: Generated<string>;
  quote_id: string;
  reason: string | null;
  tenant_id: string;
  to_status: QuoteStatus;
}

export interface Receivable {
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  category_id: string | null;
  code: Int8 | null;
  cost_center_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  issued_on: Generated<DateOnly>;
  origin: ReceivableOrigin;
  orthodontic_case_id: string | null;
  paid_cents: Generated<Int8>;
  patient_id: string;
  payer_id: string | null;
  quote_id: string | null;
  renegotiated_into_id: string | null;
  responsible_id: string | null;
  status: Generated<ReceivableStatus>;
  tenant_id: string;
  total_cents: Int8;
  treatment_plan_id: string | null;
  unit_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Referral {
  converted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  notes: string | null;
  program_id: string | null;
  referred_lead_id: string | null;
  referred_patient_id: string | null;
  referrer_name: string | null;
  referrer_patient_id: string | null;
  reward_amount_cents: Generated<Int8>;
  reward_credit_id: string | null;
  reward_granted_at: Timestamp | null;
  status: Generated<ReferralStatus>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ReferralProgram {
  created_at: Generated<Timestamp>;
  ends_on: DateOnly | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  min_ticket_cents: Generated<Int8>;
  name: string;
  reward_kind: string;
  reward_value: Generated<Int8>;
  starts_on: DateOnly | null;
  tenant_id: string;
  trigger_event: Generated<string>;
}

export interface ReportExport {
  completed_at: Timestamp | null;
  error_message: string | null;
  expires_at: Timestamp | null;
  filters: Generated<Json>;
  format: string;
  id: Generated<string>;
  report_code: string;
  requested_at: Generated<Timestamp>;
  requested_by: string | null;
  row_count: number | null;
  status: Generated<string>;
  storage_key: string | null;
  tenant_id: string;
}

export interface Resource {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: Generated<ResourceKind>;
  name: string;
  next_maintenance_on: DateOnly | null;
  tenant_id: string;
  unit_id: string;
}

export interface ResourceBooking {
  appointment_id: string | null;
  block_id: string | null;
  ends_at: Timestamp;
  id: Generated<string>;
  is_active: Generated<boolean>;
  period: Generated<string | null>;
  resource_id: string;
  starts_at: Timestamp;
  tenant_id: string;
}

export interface Role {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_system: Generated<boolean>;
  /**
   * Teto de desconto que este papel concede sozinho, em % do subtotal do orcamento.
   */
  max_discount_percent: Generated<Numeric>;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RolePermission {
  permission_key: string;
  role_id: string;
}

export interface ScheduleBlock {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  ends_at: Timestamp;
  id: Generated<string>;
  membership_id: string | null;
  notes: string | null;
  period: Generated<string | null>;
  reason: Generated<BlockReason>;
  resource_id: string | null;
  starts_at: Timestamp;
  tenant_id: string;
  unit_id: string;
}

export interface StateTransition {
  entity: string;
  from_state: string;
  is_terminal: Generated<boolean>;
  label: string;
  to_state: string;
}

export interface StockBalance {
  id: Generated<string>;
  location_id: string | null;
  lot_id: string | null;
  product_id: string;
  quantity: Generated<Numeric>;
  tenant_id: string;
  unit_id: string;
  updated_at: Generated<Timestamp>;
}

export interface StockLocation {
  code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: Generated<string>;
  name: string;
  tenant_id: string;
  unit_id: string;
}

export interface StockMovement {
  aesthetic_session_id: string | null;
  appointment_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  inventory_count_id: string | null;
  kind: StockMovementKind;
  location_id: string | null;
  lot_id: string | null;
  occurred_at: Generated<Timestamp>;
  patient_id: string | null;
  performed_by: string | null;
  product_id: string;
  quantity: Numeric;
  reason: string | null;
  tenant_id: string;
  total_cost_cents: Generated<Int8 | null>;
  transfer_group_id: string | null;
  treatment_plan_item_id: string | null;
  unit_cost_cents: Generated<Int8>;
  unit_id: string;
}

export interface SubscriptionPlan {
  billing_period: Generated<string>;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_units: number | null;
  max_users: number | null;
  name: string;
  price_cents: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface Supplier {
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  notes: string | null;
  phone: string | null;
  tax_id: string | null;
  tenant_id: string;
}

export interface SystemRolePermission {
  permission_key: string;
  role_code: string;
}

export interface Tag {
  color: Generated<string>;
  id: Generated<string>;
  kind: Generated<string>;
  name: string;
  tenant_id: string;
}

export interface Task {
  assigned_to: string | null;
  completed_at: Timestamp | null;
  completed_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  due_at: Timestamp | null;
  id: Generated<string>;
  lead_id: string | null;
  opportunity_id: string | null;
  patient_id: string | null;
  priority: Generated<string>;
  status: Generated<TaskStatus>;
  tenant_id: string;
  title: string;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface TemperatureLog {
  humidity: Numeric | null;
  id: Generated<string>;
  is_breach: Generated<boolean>;
  location_id: string;
  recorded_at: Generated<Timestamp>;
  recorded_by: string | null;
  source: Generated<string>;
  temperature: Numeric;
  tenant_id: string;
  unit_id: string;
}

export interface Tenant {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  legal_name: string;
  locale: Generated<string>;
  plan_id: string | null;
  slug: string;
  status: Generated<TenantStatus>;
  tax_id: string | null;
  timezone: Generated<string>;
  trade_name: string;
  trial_ends_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface TenantFeatureOverride {
  enabled: boolean;
  expires_at: Timestamp | null;
  feature_key: string;
  limit_value: number | null;
  note: string | null;
  tenant_id: string;
}

export interface TenantPolicy {
  block_execution_without_stock: Generated<boolean>;
  /**
   * Anos de guarda do prontuario apos o ultimo atendimento. Registra a politica; o expurgo nao e automatico.
   */
  chart_retention_years: Generated<number>;
  inactive_patient_months: Generated<number>;
  /**
   * Multa de mora, uma vez sobre o saldo vencido. Padrao 2% (CDC).
   */
  late_fine_percent: Generated<Numeric>;
  /**
   * Juros de mora ao mes, pro rata die sobre o saldo vencido. Padrao 1% (CDC).
   */
  late_interest_percent_month: Generated<Numeric>;
  no_show_risk_threshold: Generated<Numeric>;
  quote_cooling_days: Generated<number>;
  require_image_consent_for_photo: Generated<boolean>;
  require_lot_for_injectable: Generated<boolean>;
  restrict_chart_to_own_patients: Generated<boolean>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Tooth {
  arch: string;
  code: string;
  dentition: string;
  name_pt: string;
  position: number;
  quadrant: number;
  side: string;
}

export interface TreatmentPlan {
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  code: Int8 | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  diagnosis: string | null;
  id: Generated<string>;
  notes: string | null;
  patient_id: string;
  provider_id: string | null;
  quote_id: string | null;
  started_at: Timestamp | null;
  status: Generated<TreatmentPlanStatus>;
  tenant_id: string;
  title: string;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface TreatmentPlanItem {
  appointment_id: string | null;
  created_at: Generated<Timestamp>;
  description: string;
  executed_at: Timestamp | null;
  executed_by: string | null;
  id: Generated<string>;
  phase_id: string | null;
  procedure_id: string | null;
  quantity: Generated<Numeric>;
  quote_item_id: string | null;
  region_code: string | null;
  sort_order: Generated<number>;
  status: Generated<PlanItemStatus>;
  surfaces: Generated<ArrayType<ToothSurface>>;
  tenant_id: string;
  tooth_code: string | null;
  treatment_plan_id: string;
  unit_price_cents: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface TreatmentPlanPhase {
  completed_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  min_days_after_previous: Generated<number>;
  name: string;
  sort_order: number;
  started_at: Timestamp | null;
  status: Generated<string>;
  tenant_id: string;
  treatment_plan_id: string;
}

export interface Unit {
  city: string | null;
  code: string;
  complement: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  district: string | null;
  email: string | null;
  health_license: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  number: string | null;
  phone: string | null;
  state_code: string | null;
  street: string | null;
  tax_id: string | null;
  tenant_id: string;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  zip_code: string | null;
}

export interface UserSession {
  active_unit_id: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  last_seen_at: Generated<Timestamp>;
  mfa_satisfied_at: Timestamp | null;
  revoked_at: Timestamp | null;
  tenant_id: string | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface WaitlistEntry {
  created_at: Generated<Timestamp>;
  earliest_on: DateOnly | null;
  id: Generated<string>;
  latest_on: DateOnly | null;
  notes: string | null;
  offered_appointment_id: string | null;
  offered_at: Timestamp | null;
  patient_id: string;
  preferences: Generated<Json>;
  priority: Generated<number>;
  procedure_id: string | null;
  provider_id: string | null;
  scheduled_at: Timestamp | null;
  status: Generated<WaitlistStatus>;
  tenant_id: string;
  unit_id: string;
  updated_at: Generated<Timestamp>;
}

export interface WhatsappAccount {
  connected_at: Generated<Timestamp>;
  display_phone: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  phone_number_id: string;
  quality_rating: string | null;
  tenant_id: string;
  token_secret_ref: string;
  unit_id: string | null;
  verified_name: string | null;
  waba_id: string;
  webhook_secret_ref: string | null;
}

export interface DB {
  acquisition_source: AcquisitionSource;
  activity: Activity;
  aesthetic_protocol: AestheticProtocol;
  aesthetic_protocol_step: AestheticProtocolStep;
  aesthetic_session: AestheticSession;
  app_user: AppUser;
  appointment: Appointment;
  appointment_confirmation: AppointmentConfirmation;
  appointment_status_history: AppointmentStatusHistory;
  audit_log: AuditLog;
  automation_rule: AutomationRule;
  automation_run: AutomationRun;
  bank_account: BankAccount;
  bank_statement_entry: BankStatementEntry;
  body_region: BodyRegion;
  campaign: Campaign;
  cash_movement: CashMovement;
  cash_session: CashSession;
  claim: Claim;
  claim_batch: ClaimBatch;
  claim_denial: ClaimDenial;
  claim_item: ClaimItem;
  clinical_document: ClinicalDocument;
  clinical_file: ClinicalFile;
  clinical_note: ClinicalNote;
  commission_entry: CommissionEntry;
  commission_rule: CommissionRule;
  consent_document: ConsentDocument;
  conversation: Conversation;
  cost_center: CostCenter;
  financial_category: FinancialCategory;
  form_response: FormResponse;
  form_template: FormTemplate;
  gateway_charge: GatewayCharge;
  import_job: ImportJob;
  import_row: ImportRow;
  inbound_event: InboundEvent;
  injectable_application: InjectableApplication;
  installment: Installment;
  inventory_count: InventoryCount;
  inventory_count_item: InventoryCountItem;
  invitation: Invitation;
  invitation_unit: InvitationUnit;
  job: Job;
  lead: Lead;
  loss_reason: LossReason;
  membership: Membership;
  membership_unit: MembershipUnit;
  message: Message;
  message_template: MessageTemplate;
  metric_snapshot: MetricSnapshot;
  notification: Notification;
  notification_preference: NotificationPreference;
  odontogram_entry: OdontogramEntry;
  opportunity: Opportunity;
  opportunity_stage_history: OpportunityStageHistory;
  orthodontic_case: OrthodonticCase;
  orthodontic_maintenance: OrthodonticMaintenance;
  outbox_message: OutboxMessage;
  patient: Patient;
  patient_consent: PatientConsent;
  patient_contact: PatientContact;
  patient_credit: PatientCredit;
  patient_data_request: PatientDataRequest;
  patient_provider_link: PatientProviderLink;
  patient_responsible: PatientResponsible;
  patient_signal: PatientSignal;
  patient_tag: PatientTag;
  payable: Payable;
  payer: Payer;
  payment: Payment;
  payment_method: PaymentMethod;
  permission: Permission;
  phi_access_log: PhiAccessLog;
  photo_set: PhotoSet;
  photo_set_file: PhotoSetFile;
  pipeline: Pipeline;
  pipeline_stage: PipelineStage;
  plan_feature: PlanFeature;
  prescription_item: PrescriptionItem;
  price_list: PriceList;
  price_list_item: PriceListItem;
  procedure: Procedure;
  procedure_bom: ProcedureBom;
  procedure_category: ProcedureCategory;
  product: Product;
  product_lot: ProductLot;
  provider_availability: ProviderAvailability;
  purchase_order: PurchaseOrder;
  purchase_order_item: PurchaseOrderItem;
  quote: Quote;
  quote_item: QuoteItem;
  quote_status_history: QuoteStatusHistory;
  receivable: Receivable;
  referral: Referral;
  referral_program: ReferralProgram;
  report_export: ReportExport;
  resource: Resource;
  resource_booking: ResourceBooking;
  role: Role;
  role_permission: RolePermission;
  schedule_block: ScheduleBlock;
  state_transition: StateTransition;
  stock_balance: StockBalance;
  stock_location: StockLocation;
  stock_movement: StockMovement;
  subscription_plan: SubscriptionPlan;
  supplier: Supplier;
  system_role_permission: SystemRolePermission;
  tag: Tag;
  task: Task;
  temperature_log: TemperatureLog;
  tenant: Tenant;
  tenant_feature_override: TenantFeatureOverride;
  tenant_policy: TenantPolicy;
  tooth: Tooth;
  treatment_plan: TreatmentPlan;
  treatment_plan_item: TreatmentPlanItem;
  treatment_plan_phase: TreatmentPlanPhase;
  unit: Unit;
  user_session: UserSession;
  waitlist_entry: WaitlistEntry;
  whatsapp_account: WhatsappAccount;
}
